service: weather-notification

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  memorySize: 128

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    hellostepfunc1:
      definition:
        Comment: "notification of weather forecast"
        StartAt: GetWeatherForecast
        TimeoutSeconds: 60
        States:
          GetWeatherForecast:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello
            Next: Notify
          Notify:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              Subject: "test"
              Message: "test"
              TopicArn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:weather-notification
            End: true